import { ProductContentRenderer } from "../ProductContentRenderer";
import { ContentType } from "../types/ContentType";
import { a } from "./a";
import { article } from "./article";
import { audio } from "./audio";
import { b } from "./b";
import { blockquote } from "./blockquote";
import { br } from "./br";
import { code } from "./code";
import { component } from "./component";
import { componentChildren } from "./componentChildren";
import { del } from "./del";
import { div } from "./div";
import { em } from "./em";
import { errorView } from "./errorView";
import { footer } from "./footer";
import { header } from "./header";
import { hr } from "./hr";
import { i } from "./i";
import { img } from "./img";
import { li } from "./li";
import { main } from "./main";
import { nav } from "./nav";
import { ol } from "./ol";
import { p } from "./p";
import { pre } from "./pre";
import { section } from "./section";
import { span } from "./span";
import { h1 } from "./h1";
import { h2 } from "./h2";
import { h3 } from "./h3";
import { h4 } from "./h4";
import { h5 } from "./h5";
import { h6 } from "./h6";
import { strong } from "./strong";
import { sub } from "./sub";
import { sup } from "./sup";
import { table } from "./table";
import { tbody } from "./tbody";
import { td } from "./td";
import { tfoot } from "./tfoot";
import { th } from "./th";
import { thead } from "./thead";
import { tr } from "./tr";
import { u } from "./u";
import { ul } from "./ul";
import { video } from "./video";
import { view } from "./view";

export function load(): void {
  ProductContentRenderer.register(ContentType.A, a);
  ProductContentRenderer.register(ContentType.ARTICLE, article);
  ProductContentRenderer.register(ContentType.AUDIO, audio);
  ProductContentRenderer.register(ContentType.B, b);
  ProductContentRenderer.register(ContentType.BLOCKQUOTE, blockquote);
  ProductContentRenderer.register(ContentType.BR, br);
  ProductContentRenderer.register(ContentType.CODE, code);
  ProductContentRenderer.register(ContentType.COMPONENT, component);
  ProductContentRenderer.register(
    ContentType.COMPONENT_CHILDREN,
    componentChildren,
  );
  ProductContentRenderer.register(ContentType.DEL, del);
  ProductContentRenderer.register(ContentType.DIV, div);
  ProductContentRenderer.register(ContentType.EM, em);
  ProductContentRenderer.register(ContentType.ERROR_VIEW, errorView);
  ProductContentRenderer.register(ContentType.FOOTER, footer);
  ProductContentRenderer.register(ContentType.H1, h1);
  ProductContentRenderer.register(ContentType.H2, h2);
  ProductContentRenderer.register(ContentType.H3, h3);
  ProductContentRenderer.register(ContentType.H4, h4);
  ProductContentRenderer.register(ContentType.H5, h5);
  ProductContentRenderer.register(ContentType.H6, h6);
  ProductContentRenderer.register(ContentType.HEADER, header);
  ProductContentRenderer.register(ContentType.HR, hr);
  ProductContentRenderer.register(ContentType.I, i);
  ProductContentRenderer.register(ContentType.IMG, img);
  ProductContentRenderer.register(ContentType.LI, li);
  ProductContentRenderer.register(ContentType.MAIN, main);
  ProductContentRenderer.register(ContentType.NAV, nav);
  ProductContentRenderer.register(ContentType.OL, ol);
  ProductContentRenderer.register(ContentType.P, p);
  ProductContentRenderer.register(ContentType.PRE, pre);
  ProductContentRenderer.register(ContentType.SECTION, section);
  ProductContentRenderer.register(ContentType.SPAN, span);
  ProductContentRenderer.register(ContentType.STRONG, strong);
  ProductContentRenderer.register(ContentType.SUB, sub);
  ProductContentRenderer.register(ContentType.SUP, sup);
  ProductContentRenderer.register(ContentType.TABLE, table);
  ProductContentRenderer.register(ContentType.TBODY, tbody);
  ProductContentRenderer.register(ContentType.TD, td);
  ProductContentRenderer.register(ContentType.TFOOT, tfoot);
  ProductContentRenderer.register(ContentType.TH, th);
  ProductContentRenderer.register(ContentType.THEAD, thead);
  ProductContentRenderer.register(ContentType.TR, tr);
  ProductContentRenderer.register(ContentType.U, u);
  ProductContentRenderer.register(ContentType.UL, ul);
  ProductContentRenderer.register(ContentType.VIDEO, video);
  ProductContentRenderer.register(ContentType.VIEW, view);
}
